version: '2.2'
services:
    master:
        image: php:7.0-apache
        network_mode: "bridge"
        volumes:
            - ./share:/var/www/html/:ro
        ports:
            - "55060:80"
        expose:
            - "80"
        cpus: 0.02
        mem_limit: 30M
        restart: always
